### ISSUE TITLE
[Bug] BIG Eninte problem

### ISSUE THREAD

**Issue by jinnex** [Yoress/friendly-dollop#123]
Shitton of Unfriendly Enintes spawned at the same place, not even talking about that (a single) Eninte should appear only at night.
![image](https://user-images.githubusercontent.com/72616302/95654529-3400a200-0b09-11eb-8af2-c178cbe2f72a.png)

**Comment by jinnex** [comment]
Legit being followed by like 20?? 30? Enintes.
![image](https://user-images.githubusercontent.com/72616302/95654535-42e75480-0b09-11eb-95d2-54edb094458d.png)

**Comment by Yoress** [comment]
Duplicate of #70

Should be fixed.
