### ISSUE TITLE
Unable to Complete Quests with Rewards While Cube is Full -- Load Fail

### ISSUE THREAD

**Issue by Yoress** [Yoress/friendly-dollop#16]
**1.) Bug Description**
If your cube is full when completing a quest that offers item rewards, a quest load fail screen is displayed.

**2.) What you think the intended behaviour should be**
Quests should not check if a player has enough inventory space or not. The rewards should simply be added to the player's inventory and overflow it.

**3.) Steps to recreate (if not obvious)**
Fill your cube and attempt to turn in a quest that gives items as a reward.

**4.) Additional Comments (optional)**
The quest can still be completed if you clear some space in your cube. I think there might also be a message sent to the player stating that their cube is full.

**Comment by alexangc** [comment]
I suggest to simply edit the code and add the possibility to allow the overflow of the player's inventory. Suggested update in the 7z archive *(password sent on discord, remove `.txt` from the filename)*.

[cube_overflow.7z.txt](https://github.com/Yoress/friendly-dollop/files/4118895/cube_overflow.7z.txt)


- The player still can't loot or open packets when the inventory is full;
- The player can receive items from quests;
- The received item becomes automatically available once a slot is freed.

Testers can cover more exotic scenarios, if you patch the server with it.

![1_before_quest](https://user-images.githubusercontent.com/36714677/73205467-57351e00-4141-11ea-9dfd-68c6e01a4b37.png)
![2_after_quest](https://user-images.githubusercontent.com/36714677/73205468-57351e00-4141-11ea-9290-a7257a33bed6.png)
![3_after_free_slot](https://user-images.githubusercontent.com/36714677/73205469-57351e00-4141-11ea-9596-fb1e1c7861c1.png)
![3_normal_loot](https://user-images.githubusercontent.com/36714677/73205470-57351e00-4141-11ea-9808-0580479639ca.png)
![4_item_open](https://user-images.githubusercontent.com/36714677/73205473-57cdb480-4141-11ea-9785-5a433824ba7b.png)

**Comment by Yoress** [comment]
Thanks again for the help; added to the dev build.
