### ISSUE TITLE
Quest Windows Do Not Automatically Close Upon Reading/Completing 

### ISSUE THREAD

**Issue by Forthbun** [Yoress/friendly-dollop#61]
1.) Bug Description
After completing dialog/quest  dialog, the quest and/or chat window refreshes into a new page/beginning dialog. 

2.) What you think the intended behaviour should be 
The quest/chat window should automatically close on player response/dead-end dialog. 

3.) Steps to recreate (if not obvious)

4.) Additional Comments (optional)

**Comment by Yoress** [comment]
Most of the generic handling for this has been fixed; there are still several quests that individually have the wrong handling -- please report those in a collective post (see #96).
