### ISSUE TITLE
Chat Progression: Dialog with Linevir Does Not Progress

### ISSUE THREAD

**Issue by Forthbun** [Yoress/friendly-dollop#65]
**1.) Bug Description**
When speaking to Linevir (Soul Healer) in Anturoon Crossing, learning more of Soul Healing, the option "How do you heal my soul wounds?" does not progress to the next dialog. 
Linevir (ID: 203512) - Dialog (ID: 1098)
^ Dialog ID queues on GM list but does nothing. 

**2.) What you think the intended behaviour should be**
Whatever the next dialog was, I can't even remember. 

**3.) Steps to recreate (if not obvious)**

**4.) Additional Comments (optional)**

**Comment by Yoress** [comment]
![image](https://user-images.githubusercontent.com/59666778/80161277-b8279300-8584-11ea-8e65-707b7f96ff95.png)
