### ISSUE TITLE
NPC Eninte in Verteron infinitely spawns

### ISSUE THREAD

**Issue by Twinklemeow** [Yoress/friendly-dollop#70]
____________________________________________________________________
**1.) Bug Description**
Instead of spawning as a human during the day and as an undead during the night, Eninte glitches out and spawns infinitely as fast as the server allows it in both her forms in the same spot.

**2.) What you think the intended behaviour should be**
Eninte is a side-quest NPC who appears during the day as a friendly human woman and during the night as a passive(?) undead banshee. If i remember correctly, Eninte sends you on a quest to deliver a message/mcguffin to an NPC in Sanctum, after which the NPC in Sanctum shockedly informs you that Eninte has been dead for a long time and in turn, sends you on a mission to put Eninte out of her misery, for which you'll have to come back at night to kill her.

**3.) Steps to recreate (if not obvious)**
The NPC appears inside some ruins of a house in the plateau above the Contaminated Swamp in Verteron. I flew into it at //speed 300 at night. 

**4.) Additional Comments (optional)**
The area has bugged out in a different way before, so i'd rather scan it for additional fuckery. The entire area is full to the brim with timed spawns (normally plumas spawn during the day and ghosts spawn during the night, plus another ghost miniboss that spawns at night besides Eninte), which might cause spaghetti problems, given that typically timed spawns don't work on our server.
![unknown](https://user-images.githubusercontent.com/63577434/79099268-715bc100-7d6c-11ea-9950-6430ae139bc0.png)
____________________________________________________________________

**Comment by Yoress** [comment]
Should be fixed.
