### ISSUE TITLE
Quest 4912 ([Group] The Curse of Agrif's Rage) - Quest dialogue starts at the turn-in dialogue, can't start quest

### ISSUE THREAD

**Issue by kjSagee** [Yoress/friendly-dollop#78]
**1.) Quest ID**
4912

**2.) Quest Name**
[Group] The Curse of Agrif's Rage

**3.) Relevant NPC Names and ID's**
Usener, 798317

**5.) Completion Issues (if applicable)**
Can't start the quest, much less complete it.

**6.) Other Issues**
Last quest of the Agrif's Rage quest chain. Dialogue starts at the first page of reward/turn-in dialogue that is supposed to appear after killing the drake. Clicking the prompt "Here it is." brings up the housing maintenance/auction fee window and closes quest dialogue, rendering the quest unable to be started. This isn't an issue with the quest xml, which is properly formatted and has the full quest dialogue.

**Comment by Yoress** [comment]
Fixed in latest dev build.
