### ISSUE TITLE
[Mob] World Boss Gulux - Erratic Behavior 

### ISSUE THREAD

**Issue by Forthbun** [Yoress/friendly-dollop#82]
**1.) Bug Description** 
Altgard world boss Gulux fights properly then acts broken on different spawn. ID: 213005
First fight: Moment of aggro via pet, Gulux runs through and resets three times before auto-attacking spirit. Then while attacking via spirit (no direct SM skills), Gulux turns to the summoner for an auto-attack before moving back to pet. After doing so, begins to run towards Altgard fortress, climbing the wall. Resets. Re-aggros to summoner before resetting again. Killed it. 

Second fight: Repeated initiation above, appears to have fought normally. 

Third fight: Repeated initiation above, normal.

Fourth/Fifth: Done on the northern side of the map, Gulux begins resetting after engagement and acting irregular. 

**2.) What you think the intended behaviour should be**
"Normal" fights that occur on southern side of the map. 

**3.) Steps to recreate (if not obvious)**
Engage in Gulux on south and north side of the map to see if issues replicate. 

**4.) Additional Comments (optional)**
First (and Fifth) fight with the heavy glitching happened around the following coordinates: 
X = 1556.8451
Y = 1995.7208
Z = 247.375

Second two here: 
X = 1834.7717
Y = 1692.0166
Z = 247.375

Fourth: 
X = 1524.0966
Y = 1695.5808
Z = 247.88104

https://www.youtube.com/watch?v=uXL3XBFBi1k

https://www.youtube.com/watch?v=2JmsTt9VcrU

**Comment by Yoress** [comment]
This is a result of several things, the main two are:

1.) A leash in place on mobs; Gulux patrols a large area, and is too far away from his spawn location so he gives up the fight instantly. I'll be removing leashes of this nature as retail did not have a leash on mobs (with the exception of some bosses, but the leash on those is so tiny it's more of an annoyance than else).

2.) An issue with walking entities entering combat (mostly fixed on the current dev build).
