### ISSUE TITLE
Character/World: Closing Client Teleports You to Bind Point

### ISSUE THREAD

**Issue by Forthbun** [Yoress/friendly-dollop#88]
**1.) Bug Description**
When you quit the game somewhere in a zone, you are teleported to your bind point. 
Does not happen constantly, but it's often enough that it's annoying as hell. It should NOT happen at all. 

**2.) What you think the intended behaviour should be**
When you quit the game, your character should keep the precise location from where you closed the game.

**3.) Steps to recreate (if not obvious)**
Anyone else experiencing this? It's been a constant thing on my GM character, happened twice now on my normal character. 

**4.) Additional Comments (optional)**
Does not happen when you "log out" of your character to switch to another one. Only when you quit the client. 
Seems to have a timer associated with it: immediately closing client and restarting does not replicate the problem. 
What prompted me to do this report is having my client(s) closed for 40min and I log back in to my characters next to their bind points.

**Comment by Twinklemeow** [comment]
Happens to me too all the time. Super annoying.

**Comment by Forthbun** [comment]
9/22 update: Please fix this ASAP. This is extremely tilting.

**Comment by Yoress** [comment]
My focus has been elsewhere, but I'll see if I can find the issue with this.

**Comment by Yoress** [comment]
Fix pushed to test build.
